map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream nextjs_upstream {
    server 127.0.0.1:3000;
}

upstream api_upstream {
    server 127.0.0.1:3001;
}

upstream ws_upstream {
    server 127.0.0.1:3002;
}